version: '3.3'

services:
  inventoryapp:
    build: .
    image: kuldeepevon/mservices-inventory-product-app
    container_name: mservices-inventory-product-app
    ports:
      - "8090:8080"
    networks: 
      - inventory-network
    environment:
      SPRING_DATA_MONGODB_HOST: mservices-inventory-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: inventory
      PORT: 8085
  inventorydb:
    image: "mongo:latest"
    container_name: mservices-inventory-db
    restart: always
    networks: 
      - inventory-network
    # volumes: 
    #   - ./data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"


networks: 
  inventory-network:
    driver: bridge